### ISSUE TITLE
Can't "Send new password" to new users

### ISSUE THREAD

**Issue by johnsonbrothers** [Admidio/admidio#1569] opened 2024-02-06 14:15 UTC
**Describe the bug**
Starting to use Admidio, I want to invite more users to use Admidio.
But the "send password"-function is not working.

I have configured Admidio to send mail and have successfully received a Test-mail from the configuration-page.

I have Admidio in a subpath, using Nginx as reversed proxy with TLS.

**To Reproduce**
1. Go to 'Contact' and select a contact
2. Click on "Edit profile" and add a username, and check that the contacts mail-address is correct. See screenshot
3. Click on "Send new password"
4. I see a white page as the picture below but no button is working, and no mail is sent. See screenshot
5. To exit the page, press back in your browser

**Expected behavior**
I expect a dialog that ask if I want to send a "New-password"-mail.
When i press Yes, the dialog/page should return me to the contact and that he user would receive a mail.

**Screenshots**
![image](https://github.com/Admidio/admidio/assets/8428546/1d95e1e7-5437-4dec-8be6-1ea4d09cb38b)
Profile has a username

![image](https://github.com/Admidio/admidio/assets/8428546/81b27769-980e-4d80-8565-faecafd2bdc0)
Page with "send mail"-question

**System (please complete the following information):**
 - Admidio-Version - container admidio:latest [Admidio 4.3.0]
 - PHP [8.2.12 in Admidio-container 4.3.0]
 - Database [PostgreSQL]
 - Browser [firefox]
 - Browser-Version [122]

**Additional context**

source code for page with "send mail"-question
```
<div class="modal-header">
    <h3 class="modal-title">Note</h3>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">Do you want to send <strong>David Norberg</strong> an email with the current username and a new password?</div>

<div class="modal-footer">
                        <button id="admButtonYes" class="btn btn-primary" type="button" onclick="callUrlHideElement('row_members', 'https://example.com/subpath/adm_program/modules/contacts/contacts_function.php?user_uuid=04b....a7bc7&mode=4', 'Tn....Ef7')">
                <i class="fas fa-check-circle"></i>
                &nbsp;&nbsp;Yes&nbsp;&nbsp;&nbsp;
            </button>
            <button id="admButtonNo" class="btn btn-secondary" type="button" data-dismiss="modal">
                <i class="fas fa-minus-circle"></i>
                &nbsp;No
            </button>
                <div id="status-message" class="mt-4 w-100"></div>
    </div>
```

**Comment by Fasse** [comment] 2024-02-08 15:58
I can't reproduce your problem. For me the process is working. You can test it at https://www.admidio.org/playground . Just gave "Jennifer Schmidt" your email address and than use the function.

It's also strange that you doesn't get a popup dialog. Does the popup dialog in your own profile work if you want to set a new password?

**Comment by johnsonbrothers** [comment] 2024-02-09 08:45
I looked at this a bit more and compared with https://www.admidio.org/playground. I logged in as admin in both playground and in my instance.

In playground, when a Contact have a username, the button to change the password is "Change password" but in my instance the button is called "Send new password".

Where can I control whether I want to be able to "Change password", or "Send new password" by email?

**Comment by johnsonbrothers** [comment] 2024-02-09 08:53
I found one more thing...

The HTML for the buttons is different, or more precise, class is different.

This is in playground, **class="nav-link btn btn-secondary openPopup"**
```
<a id="menu_item_profile_password" class="nav-link btn btn-secondary openPopup" href="javascript:void(0);" data-href="https://...concealed.../adm_program/modules/profile/password.php?user_uuid=93ce816e-7cfd-45e1-b025-a3644828c47c"><i class="fas fa-key fa-fw"></i>Change password</a>
```

And this is in my instance, **class="nav-link btn btn-secondary**
```
<a id="menu_item_profile_send_password" class="nav-link btn btn-secondary" href="https://...concealed.../adm_program/modules/contacts/contacts_function.php?user_uuid=0e5cc814-0c6a-4ef1-a435-a8374e4bfebd&amp;mode=5">
<i class="fas fa-key fa-fw"></i>Send new password</a>
```            

_I have hidden the actual servernames_

**Comment by johnsonbrothers** [comment] 2024-02-09 09:14
Hi again!

Sorry, my bad...

I've restarted my container, the proper way, and now it works!

So sorry...

**Comment by Fasse** [comment] 2024-02-10 06:48
Ok, than I will close this issue.

**Closed** 2024-02-23 16:18 UTC
Labels: invalid
