### ISSUE TITLE
User could not create event with participation if he has not the right to manage roles

### ISSUE THREAD

**Issue by idnovic** [Admidio/admidio#1255] opened 2022-04-06 02:35 UTC
**Describe the bug**
User has edit rights to calendar "calendar1". 
The edit rights are inherited by group membership. The calendar1 gave edit rights to the group "bigGroup". 

User1 (no global calendar edit rights) 
User1 -member of> Group1
Group1 (no global calendar edit rights) 
Group1 -indirect member of> bigGroup. 
bigGroup (no global calendar edit rights) calendar1 is set to allow bigGroup to edit events. 

I am under the impression that this should work because the rights are inherited.  

User can create a new appointment. 
User is not allowed to create a new appointment if "Anmeldung zu diesem Termin ermöglichen" aka calendar invitation settings are choosen. 

**To Reproduce**
1. User with edit rights only for specific calendar and not global (edit rights given by calendar to group)
2. User adds event
3. User activates the invitation category 
4. User saves event. See error

**Expected behavior**
User can edit the invitation settings.

**Screenshots**
![15FDB7F7-1275-4751-A3CB-2952B11614FC](https://user-images.githubusercontent.com/28260793/161883896-6063c6ed-7a4c-4210-bb2d-e5dcc995a5d6.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**

**Comment by idnovic** [comment] 2022-04-07 07:29
The second user gets an error 500 if he creates calendar events

**Comment by idnovic** [comment] 2022-04-07 10:00
For both users the error only happens if the user activates the calendar invitation option.

**Comment by Fasse** [comment] 2022-04-10 14:16
I could not reproduce that error. 

In the demo area I gave the role "Mitglieder" the edit rights for the calendar "Kurse".
After that I login as "Mitglied".

I could create an event with the calendar "Kurse" and also activate the invitation option.
Maybe you have other rights or preferences also set?

**Comment by idnovic** [comment] 2022-04-11 11:57
I have the following:

User1 is part of group1. 
Both (user1 and group1) do NOT have any special rights. 
Every option under group settings is disabled. 

I added an other group group2. 
User1 is not directly part of group2. 
Instead group1 is indirect member of group2. 

I created a calendar cal1. 
This calendar is viewable by all. 
Admin and group2 have edit rights. 

user1 can create events in cal1. 
But only if no invitation settings are used. 

I can create screenshots of this helps. 
Also I would be able to provide an error log if you tell me what you need/which file I should take a look at.

**Comment by Fasse** [comment] 2022-04-12 19:04
What do you mean with group1 is indirect Part of group2?

**Comment by idnovic** [comment] 2022-04-12 19:38
> What do you mean with group1 is indirect Part of group2?

In the settings of group2 you can make all members of group1 indirect member of group2.

I mean the option "Dependencies (Optional)". 

In the settings of group2 I set the dependency on group1. 

And because user1 is member of group1,
user1 becomes member of group2 (I called this an indirect membership). 

Only group2 has edit rights for cal1, set up at the calendar options. 


That is how it is set up. And the only think I can think of why it does not work. 
But I could be wrong and the error lies somewhere else. It does not make sense to me that user1 is able to add calendar events as long as invitations settings are untouched.

**Comment by Fasse** [comment] 2022-04-13 17:50
But if the user got the right for group2 he will be assigned to that group2. This is the same assignment as if you assign him directly to group2. There is no technical difference.

**Comment by idnovic** [comment] 2022-04-13 18:25
Alright. 

I will create a test account and test your suggestion.

**Comment by idnovic** [comment] 2022-04-22 22:13
```
Fatal error: Uncaught AdmException: Role could not be saved because you
are not allowed to edit roles of this category. in
/var/www/html/admidio/adm_program/system/classes/TableRoles.php:413
Stack trace: #0
/var/www/html/admidio/adm_program/modules/dates/dates_function.php(428)
: TableRoles->save() #1 {main} thrown in
/var/www/html/admidio/adm_program/system/classes/TableRoles.php on line
413
```

**Comment by Fasse** [comment] 2022-04-23 19:59
After fixing #1261 I could reproduce your problem. I will add a fix later.

**Comment by Fasse** [comment] 2022-04-24 07:11
I found the problem and made some changes to TableRoles.php and date_functions.php . Now it should work.

**Comment by Fasse** [comment] 2022-04-24 07:11
I found the problem and made some changes to TableRoles.php and date_functions.php . Now it should work.

**Closed by Fasse** 2022-04-24 07:11 UTC
Labels: bug, module:events

**Comment by idnovic** [comment] 2022-04-28 18:30
If you are sure that the error is fixed, I will wait until the new release is out and try it again.

**Comment by idnovic** [comment] 2022-05-05 19:59
Works after the update to 4.1.11. 

Thank you
