### ISSUE TITLE
Failure to use Yes/no checkmark in list

### ISSUE THREAD

**Issue by jroselarsen** [Admidio/admidio#1221] opened 2022-02-17 12:06 UTC
**Describe the bug**
I have a public list for a group and one field in the database is used as a checkmark for privacy setting = allow to show.
In a group listing I check this field for Yes, to allow showing the member.

After the latest update, the field with the checkmark is ignored if not set as visible for all.
Showing all members of the group.
I want the field to be invisible to normal members in the group listing.

Is there any other way I may be able to use such a privacy setting?
BR Johnny

**Comment by Fasse** [comment] 2022-02-19 08:02
Could you please exactly describe which settings you have set and which not:

Field to see for all users.
Field editable only for user with permission Edit profile of all members
Mandatory field that has to be filled in always.
Field is displayed during registration

**Comment by jroselarsen** [comment] 2022-02-19 08:40
I may not have been clear on the subject:
A field can be marked as Visible for all, meaning not visible if no access to edit profiles.
If this is NOT set, and the field is used in a list with a condition, the condition does not work for groups who has no access to edit profiles. The condition is ignored.

This has worked before, without the field being shown in the listing.

Now I have to set it visible, to be able to use it as a condition in the list for these groups.

BR Johnny

**Comment by Fasse** [comment] 2022-02-21 16:32
Ok, now I understand your ticket. 

I'm not really sure if this is a bug or it was a hidden unexpected feature of the previous versions. If your are not allowed to view a field you should also not filter from that field because in your example from a checkbox field and a filter checkbox = true than I know that each user in the list has the checkbox = true status.

**Comment by Fasse** [comment] 2023-01-05 20:46
After review this issue, I think this is not a bug. It was a bug before. if you are not allowed to view a profile field than you should also not be able to filter this field.

But maybe I don't understand your issue.

You have a profile field with the setting that only users with profile edit rights could view that field.

If you are a user with profile edit rights, than you should see that field in the custom list configurator and should also filter that field.
If you are a user WITHOUT the right to edit profiles than you should not view and filter that field.

**Comment by jroselarsen** [comment] 2023-01-06 06:46
I see your point, and thanks for taking time to re-evaluate the issue.
And Happy New Year.

I've restricted the right for normal users to NOT be able to edit or create profiles.
Then I have some profiles which are public to everyone to use for viewing records.

One field is used to indicate if the record should be visible in these profiles (privacy issue due to GDPR).

And then I use the filter to enable showing the record, if the field value is true. (OK to view for all).

Before, this field did not need to be part of the fields visible in the profile.
Now it must be part of the fields visible in the frofile.

To the user, this is just nonsense, because the record is shown, thus the field is set true.

So what I need is some possibility to filter without the filter field be visible in the profile.

Does this make it clear?

BR Johnny

**Comment by Fasse** [comment] 2023-01-06 07:10
Yes I understand your feature request but I don't really understand the usecase. It would be nice for you to have such an option but I think within the project such an option will make the configuration more complex and also the understanding. Why is there a profile field within the configurator and I could not view it in the list?

**Comment by jroselarsen** [comment] 2023-01-06 07:35
It's ok to view the field, but it's just nonsense in this case, since one can only see the record if the field is set to true.

![image](https://user-images.githubusercontent.com/17494022/210952298-65239ed9-59ac-45a3-b4ea-cec4f4ece1ed.png)

In this view, the field 'Vis på medlemsliste' (show on member list) is used to allow the records to be shown.
This field is edited by the member.

It is not nescessary to show the field, since the records will not be shown if not set.

Agreed, it's a nice to have feature, but not absolutely required.

Best regards
Johnny

**Comment by Fasse** [comment] 2023-01-06 08:25
But this is a problem of every boolean field that you will filter in the configuration. But there are also usecases where it's necessary to see that field, so you know that is filtered with = "yes" .

I will close this issue with wontfix since in my opinion it's only in some cases usefull and other users maybe satisfied with the current solution.

**Closed by Fasse** 2023-01-06 08:25 UTC
Labels: enhancement, wontfix, module:lists
