### ISSUE TITLE
Error on running installation script 

### ISSUE THREAD

**Issue by SatinderpalSingh** [Admidio/admidio#779] opened 2018-05-24 03:19 UTC
I am trying to install Admidio on my linux machine, but while running the installation step in  browser, i am getting the following error:

```showText(); // => EXIT } // if database doesn't contain the components table then link to update wizard // because database Admidio version is lower then 3.0 $sql = 'SELECT 1 FROM ' . TBL_COMPONENTS; if ($gDb->queryPrepared($sql, array(), false) === false) { admRedirect(ADMIDIO_URL . '/adm_program/installation/update.php'); // => EXIT } require_once(__DIR__ . '/adm_program/system/common.php'); if (isset($gHomepage)) { admRedirect($gHomepage); // => EXIT } else { // if parameter gHomepage doesn't exists then show default page admRedirect(ADMIDIO_URL . '/adm_program/index.php'); // => EXIT }```

**Comment by Fasse** [comment] 2018-05-24 04:52
You copy Code of our script auf Not the error you gez. can you please copy the error text.

**Comment by SatinderpalSingh** [comment] 2018-05-24 05:27
This is what is visible in the browser, i am testing it on different machines and the same error occurs.
http://202.164.53.125:8088/~cc/admidio/ and on my local 
![screenshot](https://user-images.githubusercontent.com/2088760/40466005-38d21988-5f41-11e8-9072-ce7e151d0131.png)

**Comment by Fasse** [comment] 2018-05-24 05:39
Ok, strange.

**Comment by SatinderpalSingh** [comment] 2018-05-25 03:09
Yeah! it was the issue of tilde the url, now it is running on my local machine, Thanks!!
BTW, why it was not worked in the public document root, is this the default configuration or we need to change something.

**Comment by Fasse** [comment] 2018-05-25 04:28
Ok, we will try to fix this.

**Comment by ximex** [comment] 2018-06-05 14:35
@SatinderpalSingh i tried to reproduce this problem with the `~` but installation works.
is it right that you directly get the error before the first installation page?
Do you get any errors in the webserver/php/admidio log files

**Comment by Fasse** [comment] 2018-07-24 19:08
I think we should close this issue because we could not reproduce it and got no feedback.

**Closed** 2018-07-24 20:18 UTC
Labels: bug, module:installation
