### ISSUE TITLE
Error while adding another organization

### ISSUE THREAD

**Issue by Jobu** [Admidio/admidio#57] opened 2015-05-18 07:12 UTC
I tried to add another organization to my fresh 2.4.13 installation, following the documentation (http://www.admidio.org/dokuwiki/doku.php?id=de:2.0:mehrere_organisationen_verwalten). After I downloaded the config.php and wanted to proceed with the installation (.../admidio/adm_install/new_organization.php?mode=6) I got the following error:
```Fatal error: Call to a member function connect() on a non-object in .../admidio/adm_install/new_organization.php on line 64```

**Comment by Fasse** [comment] 2015-06-12 21:22
Please try it with your new 3.0-Beta.3. There we have rewritten this function.

**Comment by Jobu** [comment] 2015-06-15 05:59
The problem was that the downloaded config.php still contained the %DB_TYPE% placeholder. So, there might be a problem in your code that replaces those placeholders.

**Comment by ximex** [comment] 2015-07-18 21:21
@Jobu is this problem fixed?

**Comment by Jobu** [comment] 2015-07-20 06:26
I didn't try it with version 3. I did a workaround for my version by replacing the placeholder manually. Because of this I think this is still to be fixed FOR MY VERSION, but with an existing workaround.

**Comment by Fasse** [comment] 2015-08-04 17:28
So we should close this issue, because there is no regression in version 3. If so then reopen this issue.

**Closed by Fasse** 2015-08-04 17:28 UTC
