### ISSUE TITLE
crbug/1173575, non-JS module files deprecated

### ISSUE THREAD

**Issue by xbluemonkx** [Admidio/admidio#1528] opened 2023-11-21 20:34 UTC
**Describe the bug**
After Updating from 4.2.10 to 4.2.13 everything is running great excep, that I can not open Preferences anymore.

Firefox is showing a Blank Screen.
Chrome is showing HTTP Error 500.
Chrome Log (F12) is showing: "crbug/1173575, non-JS module files deprecated"

**To Reproduce**
1. Update to 4.2.13
2. Go to "../adm_program/modules/preferences/preferences.php"

**Expected behavior**
I would like to see settings menu instead of a blank screen / error message.

**Screenshots**

**System (please complete the following information):**
 - Admidio-Version 4.2.13
 - PHP unknown
 - Database unknown
 - Browser Firefox and Chrome

**Additional context**
- Found these Infos: https://stackoverflow.com/questions/67191286/crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%EA%9E%89530595551
- This is how the chrome error message looks like: https://i.stack.imgur.com/ZJ9nK.png

**Comment by Fasse** [comment] 2023-11-22 21:21
Duplicate of #1526

**Closed** 2023-11-22 21:22 UTC
Labels: duplicate
